language: python

python:
  - 2.7
  - 3.3
  - 3.6

install:
  - pip install pytest pytest-cov flake8 coveralls

script:
  - flake8 lettherebe --ignore=E501
  - py.test lettherebe --cov lettherebe

after_success:
  - coveralls

